# define third-party library paths
# CHANGE YOUR CUDA PATH IF IT IS NOT THIS
CUDA_DIR := /usr/local/cuda
# CHANGE YOUR CUDA ARCH IF IT IS NOT THIS
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
    -gencode arch=compute_20,code=sm_21 \
    -gencode arch=compute_30,code=sm_30 \
    -gencode arch=compute_35,code=sm_35
# CHANGE YOUR MKL PATH IF IT IS NOT THIS
MKL_DIR := /mnt/neocortex/scratch/zhangyuting/subsystem/opt/intel2/composer_xe_2013_sp1.1.106/mkl
# CHANGE YOUR MATLAB PATH IF IT IS NOT THIS
# your mex binary should be located at $(MATLAB_DIR)/bin/mex
MATLAB_DIR := /usr/local/MATLAB/R2013a
# PUT ALL OTHER INCLUDE AND LIB DIRECTORIES HERE
INCLUDE_DIRS := /mnt/neocortex/scratch/zhangyuting/subsystem/include \
	/mnt/neocortex/scratch/zhangyuting/subsystem/include/python2.7 \
	/mnt/neocortex/scratch/zhangyuting/subsystem/lib/python2.7/site-packages/numpy/core/include \
	/usr/local/include /usr/include/python2.7 \
    /usr/local/lib/python2.7/dist-packages/numpy/core/include 
LIBRARY_DIRS := /mnt/neocortex/scratch/zhangyuting/subsystem/lib \
	/usr/lib /usr/local/lib

# DEFINE THE CXX PATH
CXX=/usr/bin/g++

BUILD_DIR=build
DISTRIBUTE_DIR=distribute
